export const VIEWSTATUS = {
  GALLERY: "GALLERY",
  SPEAKER: "SPEAKER",
  FULLSCREEN: "FULLSCREEN",
  WAITING_TIME: 60,
  VOLUME_ANIMATION_INTERVAL: 800,
  MESSAGE_LIMIT: 10,
};

Object.freeze(VIEWSTATUS);
