export const EVENTSTATUS = {
    MESSAGE_EVENT: "message",
    NOTIFICATION_EVENT: "notification",
    MUTE_ALL_EVENT: "MUTE_ALL_EVENT",
    END_MEETING_EVENT: "END_MEETING_EVENT"
}

Object.freeze(EVENTSTATUS);