export const EVENTSTATUS = {
  MESSAGE_EVENT: "message",
  NOTIFICATION_EVENT: "notification",
  MUTE_ALL_EVENT: "MUTE_ALL_EVENT",
  END_MEETING_EVENT: "END_MEETING_EVENT",
  DISCONNECTED_REASON: {
    UNKNOWN_REASON: 0,
    CLIENT_INITIATED: 1,
    DUPLICATE_IDENTITY: 2,
    SERVER_SHUTDOWN: 3,
    PARTICIPANT_REMOVED: 4,
    ROOM_DELETED: 5,
    STATE_MISMATCH: 6,
    JOIN_FAILURE: 7,
    UNRECOGNIZED: -1,
  },
};

Object.freeze(EVENTSTATUS);
