export const TOGGLE_PARTICIPANTS = "TOGGLE_PARTICIPANTS";
export const TOGGLE_CHAT = "TOGGLE_CHAT";
export const CHANGE_PARTICIPANTS_COUNT = "CHANGE_PARTICIPANTS_COUNT";
export const CHANGE_UNREAD_MESSAGE_COUNT = "CHANGE_UNREAD_MESSSAGE_COUNT";
