export const GET_ROOM_DETAILS = "GET_ROOM_DETAILS";
export const CREATE_ROOM = "CREATE_ROOM";
export const SAVE_ROOM_DATA = "SAVE_ROOM_DATA";
export const SAVE_ROOM_LAYOUT = "SAVE_ROOM_LAYOUT";
export const SAVE_ROOM_CONTROLS = "SAVE_ROOM_CONTROLS";
