export const GET_ROUNDTABLES_ALL = "GET_ROUNDTABLES_ALL";
export const CREATE_ROUNDTABLE = "CREATE_ROUNDTABLE";
export const GET_ROUNDTABLE_DATA = "GET_ROUNDTABLE_DATA";
export const SAVE_PARTICIPANTS = "SAVE_PARTICIPANTS";
